on:
  pull_request: {}
  push:
    branches:
      - master

name: Run automated tests

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements.txt pytest
      - name: Run tests
        run: python -m pytest
